language: python

python:
  - '3.9'

addons:
  chrome: stable
  firefox: latest

install:
  - pip install tchappui-webdrivers

before_script:
  - sudo install-webdrivers --path /usr/local/bin/
  - pipenv install

env: DJANGO_SETTINGS_MODULE=config.settings.travis

services:
  - postgresql

script: 
  - python manage.py test