language: python

python:
  - '3.9'

addons:
  # ajouter uniquement les navigateurs utilisés
  chrome: stable
  firefox: latest
    
install:
  - pip install pipenv
  - pipenv install

before_script:
  # ajouter tchappui-webdrivers dans requirements.txt
  - install-webdrivers --path webdrivers

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script:
  - python manage.py test -v