language: python

python:
  - '3.9'

addons:
  chrome: stable
  firefox: latest

branches:
  only:
    - staging
    
install:
  - pip install pipenv
  - pipenv install

before_script:
  # pipenv install tchappui-webdrivers
  - install-webdrivers --path webdrivers

env:
  global:
    - DJANGO_SETTINGS_MODULE="config.settings.travis"

services:
  - postgresql

script:
  - python manage.py test
