language: python

python:
    - '3.9'

before_script:
    - 'pipenv install'

env: DJANGO_SETTINGS_MODULE=purbeurre_project.settings.travis

services:
    - postgresql

script: 
    - python manage.py test